apiVersion: apps/v1
kind: Deployment
metadata:
  name: satest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: satest
  template:
    metadata:
      labels:
        app: satest
    spec:
      serviceAccountName: satest
      containers:
      - image: alpine
        command:
          - /bin/sh
          - "-c"
          - "sleep 60m"
        imagePullPolicy: IfNotPresent
        name: alpine
        lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "apk add --no-cache aws-cli"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: satest
  annotations:
    eks.amazonaws.com/role-arn: <replace_role_arn>
